name = "survey-app"
main = "src/index.js"
compatibility_date = "2026-06-17"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "25-survey-app-db"
database_id = "eeca209b-e57d-45d7-a29c-ec2ef24e57dc"
